### ISSUE TITLE
The URL from CrackMe v3 gives me a 404 error.

### ISSUE THREAD

**Issue by PatatjeMC** [mrhery/CrackMe#2]
![image](https://github.com/mrhery/CrackMe/assets/85753923/5c9bb24f-2093-4373-8aa3-96f155df56a6)
When going to the URL  at from CrackMe v3 it gives me this error when it should give me the license key.

**Comment by mrhery** [comment]
We upgrading our servers. Some services are down. Can try again after few hours.

Sorry for any inconveniences.
